# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crzy < Formula
  desc "deploy your tests in less than 3 seconds."
  homepage "https://github.com/go-crzy/crzy"
  version "0.2.2"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/go-crzy/crzy/releases/download/v0.2.2/crzy_0.2.2_darwin_x86_64.tar.gz"
    sha256 "9bf49c11d22c4f3dc5bf3021cf52a343399a71574c0bcc91edd34eff888abfd0"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/go-crzy/crzy/releases/download/v0.2.2/crzy_0.2.2_darwin_arm64.tar.gz"
    sha256 "f443760eff34981050a90d9b953caad78891ff208af967ff5b2de73aaa787e1c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/go-crzy/crzy/releases/download/v0.2.2/crzy_0.2.2_linux_x86_64.tar.gz"
    sha256 "2bf822e43012262321f1d91ced6c97cdf6a48a5d3cb81bcf7da87cb40e13a932"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/go-crzy/crzy/releases/download/v0.2.2/crzy_0.2.2_linux_arm64.tar.gz"
    sha256 "5a3feb246eefb1ec5e5655b4ae8b243776f70554b76c774c6fca22629547fcd6"
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "crzy"
  end
end
