# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crzy < Formula
  desc "deploy your tests in less than 3 seconds."
  homepage "https://github.com/go-crzy/crzy"
  version "0.4.6"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-crzy/crzy/releases/download/v0.4.6/crzy_0.4.6_darwin_x86_64.tar.gz"
      sha256 "43552b462aea3ac65113bb5750fa37a256363ae3198d8f9a54a95544ac08b8d7"
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-crzy/crzy/releases/download/v0.4.6/crzy_0.4.6_darwin_arm64.tar.gz"
      sha256 "5e1e5595871f0cb1a7547e4ce71ad0b07cf745f7845839576cb162e26c70a472"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/go-crzy/crzy/releases/download/v0.4.6/crzy_0.4.6_linux_x86_64.tar.gz"
      sha256 "a32df6370865b40f2d171dc2c37cf667b54a7a216e1e52a230d57a2a142e2300"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-crzy/crzy/releases/download/v0.4.6/crzy_0.4.6_linux_arm64.tar.gz"
      sha256 "309c45262cb4ce1c57e47baaedbd4a170079ac14eff3e0ccf335fa4a73f5d195"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "crzy"
  end
end
